name: lint

on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build packages, and install the wheel
      run: |
        pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pip install black flake8 pylint
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Lint with black
      run: black --check .
    - name: Lint with flake8
      run: flake8 .
    - name: Lint with pylint
      run: pylint .
